# Generated by Django 3.2.3 on 2021-09-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(help_text='Nombre de la Categoria.', max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripcion de la Catehoria.', verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['-name'],
            },
        ),
    ]
