# Generated by Django 3.2.3 on 2021-10-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20210920_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto principal del item.', upload_to='item/', verbose_name='Foto'),
        ),
        migrations.AlterModelTable(
            name='itemmodel',
            table='item',
        ),
    ]
